lib/ceiba_web/router.ex
defmodule CeibaWeb.Router do
  use CeibaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CeibaWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/widget", WidgetController, :index
    get "/slot-detailed/:id", SlotController, :show_detailed
    resources "/slot", SlotController
    get "/slot-registration/success", SlotRegistrationController, :success
    resources "/slot-registration", SlotRegistrationController
    get "/feedback/success", FeedbackController, :success
    resources "/feedback", FeedbackController
  end

  # Other scopes may use custom stacks.
  # scope "/api", CeibaWeb do
  #   pipe_through :api
  # end
end

lib/ceiba/core/slot.ex
defmodule Ceiba.Core.Slot do
  use Ecto.Schema
  import Ecto.Changeset

  schema "slots" do
    field :email_sent_booking_closed, :boolean
    field :count_registrations, :integer, virtual: true
    embeds_one :info, Ceiba.Core.SlotInfo
    has_one :registrations, Ceiba.Core.SlotRegistration

    timestamps()
  end

  @doc false
  def changeset(slot, attrs) do
    slot
    |> cast(attrs, [:email_sent_booking_closed])
    |> cast_embed(:info)
    |> validate_required([])
  end
end

lib/ceiba_web/controllers/slot_controller.ex
defmodule CeibaWeb.SlotController do
  use CeibaWeb, :controller

  plug BasicAuth,
       [use_config: {:ceiba, :basic}]
       when action in [:index, :edit, :update, :delete, :show_detailed]

  alias Ceiba.Core
  alias Ceiba.Core.Slot

  def index(conn, params) do
    slots =
      Core.list_slots_with_feedback(params)
      |> Enum.filter(&(!String.contains?(&1.info.email || "", "krister.ee")))

    fields = CeibaWeb.SlotView.all_data_fields(slots)
    render(conn, "index.html", %{slots: slots, fields: fields})
  end

  def new(conn, _params) do
    changeset = Core.change_slot(%Slot{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"slot" => slot_params}) do
    case Core.create_slot(slot_params) do
      {:ok, slot} ->
        conn
        |> put_flash(:info, "Slot created successfully.")
        |> redirect(to: Routes.slot_path(conn, :show, slot))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    slot = Core.get_slot!(id)
    render(conn, "show.html", slot: slot)
  end

  def show_detailed(conn, %{"id" => id}) do
    slot = Core.get_slot!(id)
    registrations = Core.get_slot_registrations!(id)
    feedback = Core.get_slot_feedback(id)

    render(conn, "show-detailed.html", %{
      slot: slot,
      registrations: registrations,
      feedback: feedback
    })
  end

  def edit(conn, %{"id" => id}) do
    slot = Core.get_slot!(id)
    changeset = Core.change_slot(slot)

    render(conn, "edit.html", slot: slot, changeset: changeset)
  end

  def update(conn, %{"id" => id, "slot" => slot_params}) do
    slot = Core.get_slot!(id)

    case Core.update_slot(slot, slot_params) do
      {:ok, slot} ->
        conn
        |> put_flash(:info, "Slot updated successfully.")
        |> redirect(to: Routes.slot_path(conn, :show, slot))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", slot: slot, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    slot = Core.get_slot!(id)
    {:ok, _slot} = Core.delete_slot(slot)

    conn
    |> put_flash(:info, "Slot deleted successfully.")
    |> redirect(to: Routes.slot_path(conn, :index))
  end
end

lib/ceiba_web/views/slot_view.ex
defmodule CeibaWeb.SlotView do
  use CeibaWeb, :view
  alias Ceiba.Core

  def extra_fields do
    for embed_field <- Ceiba.Core.Slot.__schema__(:embeds),
        {:embed, embedded} = Ceiba.Core.Slot.__schema__(:type, embed_field),
        field <- embedded.related.__schema__(:fields),
        into: %{},
        do: {field, embedded.related.__schema__(:type, field)}
  end

  def count_registrations(slot_id) do
    Core.count_slots_registration(slot_id)
  end

  def config_fields do
    Application.get_env(:ceiba, Custom)[:event_types][:excursion][:slot_info_fields]
  end

  def conf_fields_feedback(role) do
    Application.get_env(:ceiba, Custom)[:feedback_questions][role]
  end

  def all_data_fields(slots) do
    default =
      case Enum.fetch(slots, 0) do
        {:ok, default} -> default
        :error -> nil
      end

    if default == nil do
      []
    else
      case Enum.find(slots, default, fn x -> x.feedback["teacher"] end) do
        slot ->
          feedback_teacher =
            Map.new(slot.feedback["teacher"] || %{}, fn {key, val} ->
              {key, val}
            end)

          feedback_student =
            Map.new(slot.feedback["student"] || %{}, fn {key, val} ->
              {key, val}
            end)

          slot.info
          |> Map.merge(feedback_teacher)
          |> Map.merge(feedback_student)
          |> Map.to_list()
      end
    end
  end

  def get_single_slot(slots) do
    default =
      case Enum.fetch(slots, 0) do
        {:ok, default} -> default
        :error -> nil
      end

    if default == nil do
      []
    else
      case Enum.find(slots, default, fn x -> x.feedback["teacher"] end) do
        slot -> slot
      end
    end
  end

  def get_status(slot) do
    cond do
      slot.count_registrations > 0 && Date.compare(slot.info.kuupaev, Date.utc_today()) == :lt ->
        "Läbitud"

      slot.count_registrations > 0 ->
        "Broneeritud"

      Date.compare(slot.info.reg_sulgemine, Date.utc_today()) == :lt ->
        "Aegunud"

      true ->
        "Uus"
    end
  end

  def count_statuses(slots) do
    Enum.reduce(slots, %{}, fn slot, acc -> Map.update(acc, get_status(slot), 1, &(&1 + 1)) end)
  end
end

lib/ceiba_web/templates/slot/edit.html.eex
<h1>Edit Slot</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.slot_path(@conn, :update, @slot)) %>

<span><%= link "Back", to: Routes.page_path(@conn, :index) %></span>

lib/ceiba_web/templates/slot/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <table class="long-input-table">

    <%= inputs_for f, :info, fn i -> %>
      <%= for details <- config_fields() do %>
        <tr>
          <td>
            <%= label i, details.key, details.label %>
          </td>
          <td>

            <%= case {details.type, details.key} do %>

              <% {:string, :piirkond} -> %>
                <%= select i, :piirkond, Application.get_env(:ceiba, Custom)[:estonia_regions] %>

              <% {:date, _} -> %>
                <%= date_select i, details.key, year: [options: 2019..2025] %>

              <% {:utc_datetime, _} -> %>
                <%= datetime_select i, details.key, year: [options: 2019..2025] %>

              <% {:string, _} -> %>
                <%= text_input i, details.key %>

              <% {:integer, _} -> %>
                <%= number_input i, details.key %>

              <% {:boolean, _} -> %>
                <%= checkbox i, details.key %>

            <% end %>
            <%= error_tag i, details.key %>
          </td>
        </tr>
      <% end %>
    <% end %>

  </table>
  <%= error_tag f, :info %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/ceiba_web/templates/slot/index.html.eex
<br/><br/>
<%= form_for @conn, "/slot", [method: :get, name: :filter_form], fn f -> %>
  <table id="filter-table">
    <tr>
      <td><p>Organisatsioon</p></td>
      <td><%= text_input f, :organisatsioon %></td>
    </tr>
    <tr>
      <td><%= submit "Filtreeri" %></td>
    </tr>
  </table>
<% end %>
<br/><br/><br/>
<h1>Kõik õppekäigud</h1>
<%= for {key, val} <- count_statuses(@slots) do %>
  <%= "#{key}: #{val}\n" %><br/>
<% end %>
<table class="full-width">
  <thead>
    <tr>
      <th>Staatus <span title="Staatus liigub järgnevalt: Uus -> Broneeritud -> Läbitud. Kui õppekäiku ei broneerita, on staatuseks Aegunud.">(?)</span></th>
      <%= for {key, _val} <- @fields, key != :__struct__, key != :id do %>
        <th><%=
          cond do
            Map.has_key?(get_single_slot(@slots).feedback["teacher"] || %{}, key) -> "Õpetaja: " <> key
            Map.has_key?(get_single_slot(@slots).feedback["student"] || %{}, key) -> "Õpilane: " <> key
            true -> key
          end
        %></th>
      <% end %>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for slot <- @slots do %>
        <tr>
          <td><%= get_status(slot) %></td>
          <%= for {key, _val} <- @fields, key != :__struct__, key != :id do %>
            <td><p><%= case Map.fetch(slot.info, key) do {:ok, val} -> val; :error -> 
              case Map.fetch(slot.feedback["teacher"] || %{}, key) do {:ok, val} -> val; :error -> 
                case Map.fetch(slot.feedback["student"] || %{}, key) do {:ok, val} -> val; :error -> "-" end 
              end 
             end %></p></td>
          <% end %>
          <td><p><%= link "Lisainfo", to: Routes.slot_path(@conn, :show_detailed, slot) %></p></td>
        </tr>
    <% end %>
  </tbody>
</table>

lib/ceiba_web/templates/slot/new.html.eex
<h1>Uus õppekäik</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.slot_path(@conn, :create)) %>

lib/ceiba_web/templates/slot/show-detailed.html.eex
<br/><br/><br/>

<h1><%= @slot.info.pealkiri %>
  <%= if count_registrations(@slot.id) == 0 do %>
  <a class="button float-right" href="/slot-registration/new?slot_id=<%= @slot.id %>">Broneeri</a>
  <% end %>
</h1>

<%= for details <- config_fields() do %>
  <strong><%= details.label %></strong>
  <%= case details.type do %>
    <% :utc_datetime -> %>
      <p><%= Map.get(@slot.info, details.key) |> Timex.format("{D}-{0M}-{YYYY}") |> elem(1) %></p>
    <% _ -> %>
      <p><%= Map.get(@slot.info, details.key) %></p>
  <% end %>
<% end %>

<br/><br/><br/><br/><br/>
<h1>Broneeringud</h1>

<ul>
  <%= for reg <- @registrations do %>
    <%= for {key, value} <- reg |> Map.from_struct,
        !Enum.member?([:id, :__meta__, :slot_id, :slot, :feedback], key)
    do %>
      <%= if key == :info do %>
        <%= for {sub_key, sub_value} <- value |> Map.from_struct, sub_key != :id do %>
          <li>
            <strong><%= Phoenix.Naming.humanize sub_key %></strong>
            <%= sub_value %>
          </li>
        <% end %>
      <% else %>
        <li>
          <strong><%= Phoenix.Naming.humanize key %></strong>
          <%= value %>
        </li>
      <% end %>
    <% end %>
    <br/>
    <p><%= link "Tagasiside link õpetajale", to: Routes.feedback_path(@conn, :new, %{reg_id: reg.id, r: "teacher"}) %></p>
    <p><%= link "Tagasiside link õpilasele", to: Routes.feedback_path(@conn, :new, %{reg_id: reg.id, r: "student"}) %></p>
  <% end %>
</ul>

<br/>
<h1>Tagasiside</h1>

<%= for fb <- @feedback do %>
  <div class="gridish">
    <h2><%= fb.role %></h2>

    <%= for {key, value} <- fb.info do %>
      <strong><%= CeibaWeb.ViewHelpers.key_to_question(
        Application.get_env(:ceiba, Custom)[:feedback_questions][fb.role],
        key,
        @slot.info.opieesmark
      ) %></strong>
      <p><%= value %></p>
    <% end %>
  </div>
<% end %>

lib/ceiba_web/templates/slot/show.html.eex
<br/><br/><br/>

<h1><%= @slot.info.pealkiri %>
  <%= if count_registrations(@slot.id) == 0 do %>
  <a class="button float-right" href="/slot-registration/new?slot_id=<%= @slot.id %>">Broneeri</a>
  <% end %>
</h1>

<%= for details <- config_fields() do %>
  <p style="margin: 0;">
    <b><%= details.label_short %>:&nbsp;</b>
    <%= case details.type do %>
      <% :utc_datetime -> %>
        <%= Map.get(@slot.info, details.key) |> Timex.format("{D}-{0M}-{YYYY}") |> elem(1) %>
      <% _ -> %>
        <%= Map.get(@slot.info, details.key) %>
    <% end %>
  </p>
<% end %>