lib/ceiba_web/router.ex
defmodule CeibaWeb.Router do
  use CeibaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CeibaWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/widget", WidgetController, :index
    get "/slot-detailed/:id", SlotController, :show_detailed
    resources "/slot", SlotController
    get "/slot-registration/success", SlotRegistrationController, :success
    resources "/slot-registration", SlotRegistrationController
    get "/feedback/success", FeedbackController, :success
    resources "/feedback", FeedbackController
  end

  # Other scopes may use custom stacks.
  # scope "/api", CeibaWeb do
  #   pipe_through :api
  # end
end

lib/ceiba/core/feedback.ex
defmodule Ceiba.Core.Feedback do
  use Ecto.Schema
  import Ecto.Changeset

  schema "feedback" do
    field :info, :map
    field :role, :string
    belongs_to :slot_registration, Ceiba.Core.SlotRegistration

    timestamps()
  end

  @doc false
  def changeset(feedback, attrs) do
    attrs =
      if Map.has_key?(attrs, "info") and is_bitstring(attrs["info"]) do
        Map.replace!(attrs, "info", Poison.decode!(attrs["info"]))
      else
        attrs
      end

    feedback
    |> cast(attrs, [:info, :slot_registration_id, :role])
    |> validate_required([:info, :slot_registration_id, :role])
  end
end

lib/ceiba_web/controllers/feedback_controller.ex
defmodule CeibaWeb.FeedbackController do
  use CeibaWeb, :controller

  plug BasicAuth,
       [use_config: {:ceiba, :basic}] when action in [:index, :show, :edit, :update, :delete]

  alias Ceiba.Core
  alias Ceiba.Core.Feedback

  def index(conn, _params) do
    feedback = Core.list_feedback()
    render(conn, "index.html", feedback: feedback)
  end

  def new(conn, %{"reg_id" => reg_id, "r" => role}) do
    registration = Core.get_slot_registration!(reg_id)
    slot = Core.get_slot!(registration.slot_id)
    changeset = Core.change_feedback(%Feedback{slot_registration_id: reg_id, role: role})

    render(conn, "new.html", %{
      changeset: changeset,
      registration: registration,
      slot: slot,
      role: role
    })
  end

  def create(conn, %{"feedback" => feedback_params}) do
    registration = Core.get_slot_registration!(feedback_params["slot_registration_id"])
    slot = Core.get_slot!(registration.slot_id)

    case Core.create_feedback(feedback_params) do
      {:ok, feedback} ->
        conn
        |> put_flash(:info, "Feedback created successfully.")
        |> redirect(to: Routes.feedback_path(conn, :success, %{}))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", %{changeset: changeset, registration: registration, slot: slot})
    end
  end

  def success(conn, _params) do
    render(conn, "success.html")
  end

  def show(conn, %{"id" => id}) do
    feedback = Core.get_feedback!(id)
    registration = Core.get_slot_registration!(feedback.slot_registration_id)
    slot = Core.get_slot!(registration.slot_id)
    render(conn, "show.html", %{feedback: feedback, slot: slot})
  end

  def update(conn, %{"id" => id, "feedback" => feedback_params}) do
    feedback = Core.get_feedback!(id)

    case Core.update_feedback(feedback, feedback_params) do
      {:ok, feedback} ->
        conn
        |> put_flash(:info, "Feedback updated successfully.")
        |> redirect(to: Routes.feedback_path(conn, :show, feedback))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", feedback: feedback, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    feedback = Core.get_feedback!(id)
    {:ok, _feedback} = Core.delete_feedback(feedback)

    conn
    |> put_flash(:info, "Feedback deleted successfully.")
    |> redirect(to: Routes.feedback_path(conn, :index))
  end
end

lib/ceiba_web/views/feedback_view.ex
defmodule CeibaWeb.FeedbackView do
  use CeibaWeb, :view

  def config_fields(role) do
    Application.get_env(:ceiba, Custom)[:feedback_questions][role]
  end
end

lib/ceiba_web/templates/feedback/edit.html.eex
<h1>Edit Feedback</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.feedback_path(@conn, :update, @feedback)) %>

<span><%= link "Back", to: Routes.feedback_path(@conn, :index) %></span>

lib/ceiba_web/templates/feedback/form.html.eex
<%= form_for @conn, Routes.feedback_path(@conn, :new), [id: "placeholder_form"], fn i -> %>
  <%= for details <- Application.get_env(:ceiba, Custom)[:feedback_questions][@role] do %>
    <%= label i, details.key, CeibaWeb.ViewHelpers.get_label(details, @slot.info.opieesmark) %>
      <div>
        <%= case details.type do %>
          <% :score5 -> %>
            <span>Ei nõustu üldse</span>
            <span>1 <%= radio_button i, details.key, 1 %></span>
            <span>2 <%= radio_button i, details.key, 2 %></span>
            <span>3 <%= radio_button i, details.key, 3 %></span>
            <span>4 <%= radio_button i, details.key, 4 %></span>
            <span>5 <%= radio_button i, details.key, 5 %></span>
            <span>Nõustun täielikult</span>
          <% :score5agree -> %>
            <span>Ei nõustu üldse</span>
            <span>1 <%= radio_button i, details.key, 1 %></span>
            <span>2 <%= radio_button i, details.key, 2 %></span>
            <span>3 <%= radio_button i, details.key, 3 %></span>
            <span>4 <%= radio_button i, details.key, 4 %></span>
            <span>5 <%= radio_button i, details.key, 5 %></span>
            <span>Nõustun täielikult</span>
          <% :score10 -> %>
            <span>Ei nõustu üldse</span>
            <span>1 <%= radio_button i, details.key, 1 %></span>
            <span>2 <%= radio_button i, details.key, 2 %></span>
            <span>3 <%= radio_button i, details.key, 3 %></span>
            <span>4 <%= radio_button i, details.key, 4 %></span>
            <span>5 <%= radio_button i, details.key, 6 %></span>
            <span>6 <%= radio_button i, details.key, 5 %></span>
            <span>7 <%= radio_button i, details.key, 7 %></span>
            <span>8 <%= radio_button i, details.key, 8 %></span>
            <span>9 <%= radio_button i, details.key, 9 %></span>
            <span>10 <%= radio_button i, details.key, 10 %></span>
            <span>Nõustun täielikult</span>

          <% :integer -> %>
            <%= number_input i, details.key %>

          <% :string -> %>
            <%= text_input i, details.key %>

          <% :boolean -> %>
            <%= checkbox i, details.key %>
        <% end %>
        <%= error_tag i, details.key %>
      </div>
      <br/>
      <br/>
  <% end %>
<% end %>



<%= form_for @changeset, @action, [id: "real_form"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors above.</p>
    </div>
  <% end %>

  <%= hidden_input f, :slot_registration_id %>
  <%= error_tag f, :slot_registration_id %>
  <%= hidden_input f, :info %>
  <%= error_tag f, :info %>
  <%= hidden_input f, :role %>
  <%= error_tag f, :role %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

<script>
  // form to :info map
	function toJSONString( form ) {
		var obj = {};
		var elements = form.querySelectorAll('input:not([type="hidden"]):not([type="radio"]), input[type="radio"]:checked')
    console.log(elements)
		for( var i = 0; i < elements.length; ++i ) {
			var element = elements[i];
			var name = element.name;
			var value = element.value;

			if( name ) {
				obj[ name ] = value;
			}
		}

		return JSON.stringify( obj );
	}

	document.addEventListener( "DOMContentLoaded", function() {
		var form = document.getElementById( "placeholder_form" );
		var real_form = document.getElementById( "real_form" );
		form.addEventListener( "change", function( e ) {
			e.preventDefault();
			var json = toJSONString( this );
      console.log(json)
			document.querySelector('#feedback_info').value = json

		}, false);

	});

</script>

lib/ceiba_web/templates/feedback/index.html.eex
<h1>Listing Feedback</h1>

<table>
  <thead>
    <tr>
      <th>Info</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for feedback <- @feedback do %>
    <tr>
      <td><%= # feedback.info %></td>

      <td>
        <%= link "Show", to: Routes.feedback_path(@conn, :show, feedback) %>
        <%= link "Edit", to: Routes.feedback_path(@conn, :edit, feedback) %>
        <%= link "Delete", to: Routes.feedback_path(@conn, :delete, feedback), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Feedback", to: Routes.feedback_path(@conn, :new) %></span>

lib/ceiba_web/templates/feedback/new.html.eex
<h1>Tagasiside õppekäigule</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.feedback_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.feedback_path(@conn, :index) %></span>

lib/ceiba_web/templates/feedback/show.html.eex
<h1>Tagasiside</h1>


  <%= for {key, value} <- @feedback.info, key != :id do %>
      <strong><%= CeibaWeb.ViewHelpers.key_to_question(config_fields(@feedback.role), key, @slot.info.opieesmark) %></strong>
      <p><%= value %></p>
  <% end %>

<p><%= link "Tagasi õppekäigu juurde", to: Routes.slot_path(@conn, :show, @slot.id) %></p>

lib/ceiba_web/templates/feedback/success.html.eex
<p>Aitäh Sulle tagasiside eest!</p>